# Generated by Django 5.0.3 on 2024-03-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='security',
        ),
    ]
